language: rust
rust:
- stable
- beta
- nightly
notifications:
  email:
  - mitchell.nordine@gmail.com
os:
- osx
before_script:
- rustc --version
- cargo --version
- rustup component add rustfmt
script:
- cargo build --verbose
- cargo test --verbose
